/* Английский перевод. Ключ — русская строка, значение — английская.
   Данные (герои, оружие, враги, сюжет, патчноуты) переводятся на месте при загрузке,
   строки интерфейса — через _t(), статичный HTML — обходом текста страницы. */
const EN={
/* ---------- герои ---------- */
'Пеструшка':'Speckles',
'Сбалансированная, берёт в бой лишнее яйцо':'Well-rounded, carries an extra egg into battle',
'Яичный дождь':'Egg Rain',
'Одна зона там, где врагов гуще всего: в неё падают 8 яиц-бомб':'One zone where enemies are thickest: 8 egg bombs rain into it',
'Запасливая':'Thrifty',
'Каждая новая волна даёт +1 яйцо-гранату':'Every new wave gives +1 egg grenade',
'Наседка':'Mother Hen',
'Кукуруза лечит вдвое сильнее и падает в полтора раза чаще':'Corn heals twice as much and drops 1.5× as often',
'Цыпа Шустрик':'Zippy Chick',
'Мелкий и быстрый, +25% темпа стрельбы':'Small and fast, +25% fire rate',
'Турбо-пух':'Turbo Fluff',
'4 секунды двойной скорости и двойного темпа стрельбы':'4 seconds of double speed and double fire rate',
'Увёртливый':'Dodgy',
'15% шанс, что яйцо пролетит мимо':'15% chance an egg misses you',
'Пух-реактор':'Fluff Reactor',
'Ульта копится на 40% быстрее':'Ultimate charges 40% faster',
'Петя Шпора':'Pete Spur',
'Крепкий задира, +15% урона':'Tough brawler, +15% damage',
'Боевой клич':'Battle Cry',
'«КУКАРЕКУ!» оглушает всех рядом на 2,5 с и бьёт на 45':'“COCK-A-DOODLE-DOO!” stuns everyone nearby for 2.5 s and deals 45',
'Шпоры':'Spurs',
'Кто кусает Петю, сам получает 20 урона':'Whoever bites Pete takes 20 damage',
'Задира':'Bully',
'15% шанс критического удара ×2':'15% chance of a ×2 critical hit',
'Утка Кря':'Quacky Duck',
'Лечится сама, если 4 секунды не получала урон':'Heals herself after 4 seconds without damage',
'Кря-волна':'Quack Wave',
'Лечит половину здоровья, сбивает яйца и отталкивает врагов':'Heals half HP, knocks down eggs and pushes enemies away',
'Непромокаемая':'Waterproof',
'Получает на 10% меньше урона':'Takes 10% less damage',
'Второе дыхание':'Second Wind',
'Один раз за бой встаёт с 50% здоровья':'Once per battle gets back up with 50% HP',
'Гусь Бронебой':'Ironclad Goose',
'Толстые перья: на 25% меньше урона':'Thick feathers: 25% less damage',
'Гусиная крепость':'Goose Fortress',
'5 секунд неуязвимости, вражеские яйца отлетают обратно':'5 seconds of invulnerability, enemy eggs bounce back',
'Шипение':'Hiss',
'Враги рядом с гусём двигаются на 30% медленнее':'Enemies near the goose move 30% slower',
'Бронеперья':'Armor Feathers',
'Ещё −15% получаемого урона':'Another −15% damage taken',
'Перепёлка Тень':'Shadow Quail',
'Тихая и меткая: +15% урона':'Quiet and accurate: +15% damage',
'Теневой выстрел':'Shadow Shot',
'Три пробивающих луча в самых крепких врагов на экране':'Three piercing beams at the toughest enemies on screen',
'Зоркий глаз':'Keen Eye',
'+25% урона по целям дальше 250':'+25% damage to targets farther than 250',
'Охотница':'Huntress',
'Убийство издалека заряжает ульту на 10%':'Long-range kills charge the ultimate by 10%',
'Цесарка Буря':'Storm Guinea',
'Шустрая боевая птица в горошек':'A nimble polka-dot war bird',
'Перьевой ураган':'Feather Hurricane',
'4 секунды вихрь вокруг бьёт и отбрасывает врагов и сбивает их пули':'For 4 seconds a whirlwind hits and throws back enemies and knocks down their shots',
'Пёстрые перья':'Dazzling Feathers',
'10% шанс увернуться от любого урона':'10% chance to dodge any damage',
'Неугомонная':'Restless',
'+15% темпа стрельбы':'+15% fire rate',
'Гусыня Медсестра':'Nurse Goose',
'Заботливая: получает на 10% меньше урона':'Caring: takes 10% less damage',
'Полевой госпиталь':'Field Hospital',
'6 секунд зона лечения: лечит всех своих и сразу поднимает выбитых бойцов':'A 6-second healing zone: heals all allies and instantly revives downed fighters',
'Перевязка':'Bandage',
'Выбитые бойцы отряда возвращаются через 9 с вместо 18':'Downed squad members return after 9 s instead of 18',
'Милосердие':'Mercy',
'Лечение класса «Медик» вдвое сильнее':'Medic class healing is twice as strong',
'Боевой Петушок Adrenaline':'Battle Rooster Adrenaline',
'Легенда двора: быстрее, крепче и злее всех':'Legend of the yard: faster, tougher and angrier than anyone',
'Адреналин':'Adrenaline',
'6 секунд ярости: огненные кольца пуль и +40% скорости':'6 seconds of rage: rings of fire bullets and +40% speed',
'Кровь кипит':'Boiling Blood',
'+30% урона, когда здоровья меньше половины':'+30% damage when below half HP',
'Неудержимый':'Unstoppable',
'Убийства лечат 3 здоровья, ярость длится на 2 с дольше':'Kills heal 3 HP, rage lasts 2 s longer',
/* ---------- оружие ---------- */
'Пугач':'Popgun',
'Надёжный стартовый ствол':'A reliable starter gun',
'Шериф':'Sheriff',
'Медленный, но бьёт вдвое сильнее':'Slow, but hits twice as hard',
'Пшеномёт':'Millet Gun',
'Поливает двор очередями':'Sprays the yard with bursts',
'Обрез':'Sawed-off',
'Разносит всё вблизи':'Wrecks everything up close',
'Попкорн-бластер':'Popcorn Blaster',
'Зерно прошивает сразу трёх врагов':'Each kernel pierces three enemies',
'Морозилка':'Freezer',
'Ледяные иглы замедляют врагов вдвое':'Ice needles slow enemies by half',
'Урон 10 · 10 выстр/с · замедление 50%':'Damage 10 · 10 shots/s · 50% slow',
'Огнемёт «Жар-птица»':'Firebird Flamethrower',
'Струя огня поджигает всех врагов перед тобой':'A stream of fire sets every enemy in front of you ablaze',
'Урон 5 × 20/с + горение 9/с · дальность средняя':'Damage 5 × 20/s + burn 9/s · medium range',
'Миниган «Молотилка»':'Thresher Minigun',
'Раскручивается до бешеного темпа, но на бегу тормозит':'Spins up to a crazy rate, but slows you down while running',
'Урон 11 · до 22 выстр/с после раскрутки':'Damage 11 · up to 22 shots/s when spun up',
'Яйцемёт':'Egg Mortar',
'Навесом кидает взрывные яйца, каждый задетый враг лечит своих':'Lobs explosive eggs; every enemy hit heals your team',
'Взрыв 65 по площади · +2 здоровья за врага':'65 area damage · +2 HP per enemy hit',
'Бабушкин дробовик':'Granny’s Shotgun',
'Старый, но надёжный дробовик танка':'An old but trusty tank shotgun',
'Кукурузная винтовка':'Corn Rifle',
'Меткий дальний выстрел, прошивает двоих':'Accurate long shot that pierces two',
'Арбалет «Клюв»':'Beak Crossbow',
'Тяжёлый болт пробивает четверых подряд':'A heavy bolt pierces four in a row',
'Шприцемёт':'Syringe Gun',
'Каждое попадание лечит тебя и бойца рядом':'Every hit heals you and a nearby ally',
'Урон 17 · 4 выстр/с · +1 здоровья за попадание':'Damage 17 · 4 shots/s · +1 HP per hit',
'Витаминный пулемёт':'Vitamin Machine Gun',
'Очереди витаминок: бьют врагов и лечат своих':'Bursts of vitamins: hurt enemies and heal allies',
'Урон 10 · 10 выстр/с · +0,5 здоровья за попадание':'Damage 10 · 10 shots/s · +0.5 HP per hit',
'Рельсотрон':'Railgun',
'Луч прошивает всех врагов и даже укрытия на линии':'The beam pierces every enemy and even cover in its line',
'Урон 130 всем на линии · раз в секунду':'130 damage to everything in line · once per second',
'Пулемёт Турбокота':'Turbo Cat Machine Gun',
'Мурчит очередями, а каждый 6-й выстрел — турбо-клубок':'Purrs out bursts, and every 6th shot is a turbo yarn ball',
'Урон 12 · 14 выстр/с · каждый 6-й — клубок ×3, пробивает двоих':'Damage 12 · 14 shots/s · every 6th is a ×3 yarn ball that pierces two',
'Дробовик Фигурки':'Shapes Shotgun',
'Стреляет звёздочками, сердечками и кубиками — они отскакивают от укрытий':'Fires stars, hearts and cubes that bounce off cover',
'Урон 13×6 · дробинки-фигурки рикошетят один раз':'Damage 13×6 · shape pellets ricochet once',
'Дробовик':'Shotgun',
'Тарахтелка':'Rattler',
/* ---------- классы, редкости, скины ---------- */
'Штурмовик':'Assault','+10% скорости и темпа стрельбы':'+10% speed and fire rate',
'Танк':'Tank','+25% здоровья и −10% входящего урона, но на 8% медленнее':'+25% HP and −10% damage taken, but 8% slower',
'Снайпер':'Sniper','+20% урона и пули летят на 35% дальше, но −10% здоровья':'+20% damage and bullets fly 35% farther, but −10% HP',
'Медик':'Medic','Лечится на 1,2 в секунду, лечит всех своих рядом и вдвое быстрее поднимает выбитых бойцов':'Heals 1.2 HP per second, heals all nearby allies and revives downed fighters twice as fast',
'Обычный':'Common','Редкий':'Rare','Эпический':'Epic','Легендарный':'Legendary',
'Обычное':'Common','Редкое':'Rare','Легендарное':'Legendary',
'Без шапки':'No hat','Бандана':'Bandana','Каска':'Helmet','Ковбойская шляпа':'Cowboy hat','Пират':'Pirate','Ниндзя':'Ninja','Корона':'Crown','Нимб':'Halo',
'Родной окрас':'Natural','Розовый':'Pink','Мятный':'Mint','Ночной':'Night','Золотое перо':'Golden feather','Платиновый':'Platinum',
/* ---------- враги ---------- */
'Несушка':'Hen','Лиса':'Fox','Индюк':'Turkey','Ворона':'Crow','Енот':'Raccoon','Мышь':'Mouse','Крыса':'Rat','Волк':'Wolf','Сова':'Owl','Хорёк':'Ferret',
'Робо-несушка':'Robo-Hen','Крот':'Mole','Орёл':'Eagle',
'Индюк-генерал':'General Turkey','Ко мне, солдаты!':'To me, soldiers!',
'Лис-атаман':'Fox Chieftain','Банда, за мной!':'Gang, follow me!',
'Барсук-Бульдозер':'Bulldozer Badger','Разойдись — снесу!':'Out of my way!',
'Вожак Серый Хвост':'Greytail the Pack Leader','Ау-у-у! Стая, ко мне!':'Awooo! Pack, to me!',
'Стальной Индюк':'Steel Turkey','ПРОТОКОЛ «ОЩИПАТЬ» ЗАПУЩЕН':'PROTOCOL “PLUCK” ENGAGED',
'Доктор Хорёк':'Doctor Ferret','Мои творения, в атаку!':'My creations, attack!',
'Орёл Буревестник':'Stormbringer Eagle','С неба не уйдёшь!':'You can’t escape the sky!',
'Император Ворон':'Emperor Raven','Склонитесь перед Императором!':'Bow before the Emperor!',
'Кроты':'Moles','Враги':'Enemies','Лисы':'Foxes','Вороны':'Crows','Индюки':'Turkeys','Волки':'Wolves','Совы':'Owls','Робо-несушки':'Robo-Hens',
'Мыши':'Mice','Крысы':'Rats','Хорьки':'Ferrets','Орлы':'Eagles','Еноты':'Raccoons','Несушки':'Hens',
/* ---------- сюжет: глава 1 ---------- */
'Курятник в беде':'The Coop in Trouble',
'Тихое утро на ферме кончилось: банда Лиса-атамана решила забрать наш курятник. Сначала он шлёт мелочь — но за ней придут и другие.':'The quiet farm morning is over: the Fox Chieftain’s gang wants our coop. First he sends small fry — but bigger trouble will follow.',
'Атаман повержен! Убегая, он прокричал: «Серый Хвост за меня отомстит!» Следы банды ведут в Тёмный лес.':'The Chieftain is beaten! Running off, he yelled: “Greytail will avenge me!” The gang’s tracks lead into the Dark Forest.',
'Тревога в курятнике':'Alarm in the Coop','Чужие несушки лезут через забор. Покажи им, кто тут главный.':'Strange hens are climbing the fence. Show them who’s boss.',
'Зерновой налёт':'Grain Raid','Крысы почуяли запах пшена. Не подпускай их к амбару 40 секунд.':'The rats smelled the millet. Keep them away from the barn for 40 seconds.',
'Лисьи следы':'Fox Tracks','У забора рыжая шерсть: лисы сделали подкоп. Прогони 8 лис.':'Red fur by the fence: the foxes dug a tunnel. Chase off 8 foxes.',
'Пропавший цыплёнок':'The Missing Chick','Наседки пересчитали цыплят — одного не хватает. Пробейся через три волны и найди его.':'The mother hens counted their chicks — one is missing. Fight through three waves and find it.',
'Чёрные крылья':'Black Wings','Вороны кидают яйца с неба. Уходи из красных кругов и сбей 8 ворон.':'Crows drop eggs from the sky. Get out of the red circles and shoot down 8 crows.',
'Индюшиный дозор':'Turkey Patrol','Индюки-разведчики осматривают двор. Не дай им вернуться к своему генералу.':'Turkey scouts are inspecting the yard. Don’t let them report back to their general.',
'Ночь у амбара':'Night at the Barn','Ночью у амбара кто-то шуршит. Это еноты! Пройди три волны в темноте.':'Something rustles by the barn at night. Raccoons! Clear three waves in the dark.',
'Засада у колодца':'Ambush at the Well','Цыплёнок нашёлся у колодца, но вокруг засада. Держись минуту, пока его уводят домой.':'The chick turned up by the well, but it’s an ambush. Hold out for a minute while it’s led home.',
'Шпионки в перьях':'Feathered Spies','Среди наших несушек затесались шпионки генерала. Победи 25 врагов.':'The general’s spies are hiding among our hens. Defeat 25 enemies.',
'Генерал лично привёл армию к нашему забору. Сбей с него фуражку!':'The general himself has led his army to our fence. Knock his cap off!',
'Прикрытие генерала':'The General’s Rearguard','Генерал сбежал, но оставил прикрытие. Пройди три волны.':'The general fled but left a rearguard. Clear three waves.',
'Крысиный король':'The Rat King','Крысы собрались в огромную стаю. Продержись минуту.':'The rats have gathered into a huge swarm. Hold out for a minute.',
'Новый подкоп':'A New Tunnel','Лисы роют ход прямо под насест. Прогони 15 лис.':'The foxes are digging right under the roost. Chase off 15 foxes.',
'Вороний патруль':'Crow Patrol','Вороны кружат над двором с утра до вечера. Отбей три волны.':'Crows circle the yard from dawn to dusk. Repel three waves.',
'Тёмный сарай':'The Dark Shed','В сарае погас свет. Держись 75 секунд, пока Петя чинит фонарь.':'The lights went out in the shed. Hold out for 75 seconds while Pete fixes the lamp.',
'Перехваченное письмо':'The Intercepted Letter','Ворона уронила письмо: «Атаман нападёт на рассвете». Готовься — победи 35 врагов.':'A crow dropped a letter: “The Chieftain attacks at dawn.” Get ready — defeat 35 enemies.',
'Рассвет':'Dawn','Солнце встаёт, а вместе с ним — вся банда. Пройди четыре волны.':'The sun rises, and so does the whole gang. Clear four waves.',
'Последний забор':'The Last Fence','Забор трещит. Продержись 90 секунд, пока несушки ставят подпорки.':'The fence is cracking. Hold out for 90 seconds while the hens prop it up.',
'Перед бурей':'Before the Storm','Ночь перед решающим боем. Банда идёт в последний натиск: победи 45 врагов.':'The night before the decisive battle. The gang makes its final push: defeat 45 enemies.',
'Главарь банды пришёл сам. Это решающий бой за курятник!':'The gang leader came himself. This is the decisive battle for the coop!',
/* ---------- глава 2 ---------- */
'Тёмный лес':'Dark Forest',
'Следы банды ведут в Тёмный лес. Здесь правит волчья стая Серого Хвоста, а совы-снайперы сторожат каждую тропу.':'The gang’s tracks lead into the Dark Forest. Greytail’s wolf pack rules here, and sniper owls guard every path.',
'Вожак сдался и выдал тайну: банду снабжал Доктор Хорёк. На своей птицефабрике он строит армию роботов.':'The pack leader gave up and spilled the secret: Doctor Ferret supplied the gang. He’s building a robot army at his poultry factory.',
'Опушка':'Forest Edge','Ты у края леса. Беглые лисы атамана прячутся за пнями.':'You’re at the edge of the forest. The Chieftain’s runaway foxes hide behind the stumps.',
'Волчий вой':'Wolf Howl','Из чащи слышен вой. Волчата проверяют твою храбрость — прогони шестерых.':'Howling echoes from the thicket. Wolf cubs are testing your courage — chase off six.',
'Совиный глаз':'Owl Eye','Совы целятся издалека — перед выстрелом видна красная линия прицела. Сбей пять сов.':'Owls aim from afar — a red aiming line shows before they shoot. Shoot down five owls.',
'Тропа енотов':'Raccoon Trail','Еноты устроили засаду на узкой тропе. Продержись 50 секунд.':'Raccoons set an ambush on a narrow trail. Hold out for 50 seconds.',
'Ночная поляна':'Night Glade','Ночью в лесу темнее, чем на ферме. Пройди три волны.':'Night in the forest is darker than on the farm. Clear three waves.',
'Ягодник':'Berry Patch','Ягодник сторожат часовые Серого Хвоста. Победи 25 врагов.':'Greytail’s sentries guard the berry patch. Defeat 25 enemies.',
'Старый дуб':'The Old Oak','К старому дубу слетелись совы и вороны. Держись минуту.':'Owls and crows have flocked to the old oak. Hold out for a minute.',
'Волчья тропа':'Wolf Trail','Волки идут по твоему следу. Отбей три волны.':'Wolves are on your trail. Repel three waves.',
'Туманное болото':'Foggy Swamp','На болоте туман и темень. Победи 30 врагов и не увязни.':'Fog and darkness on the swamp. Defeat 30 enemies and don’t get stuck.',
'Барсук сносит деревья, как спички. Останови его!':'The badger snaps trees like matches. Stop him!',
'Сломанная плотина':'The Broken Dam','Барсук сломал бобровую плотину — вода гонит врагов прямо на тебя.':'The badger broke the beaver dam — the water is driving enemies straight at you.',
'Совиный совет':'Owl Council','Совы собрались на тайный совет. Сорви его — сбей десять сов.':'The owls are holding a secret council. Break it up — shoot down ten owls.',
'Гнилой мост':'The Rotten Bridge','Мост скрипит под лапами. Продержись минуту, пока цыплята переходят.':'The bridge creaks underfoot. Hold out for a minute while the chicks cross.',
'Лисья нора':'Fox Den','Здесь прячутся последние лисы атамана. Найди двадцать.':'The Chieftain’s last foxes are hiding here. Find twenty.',
'Запах логова':'Scent of the Lair','Пахнет волком — логово близко. Пройди четыре волны.':'It smells of wolf — the lair is close. Clear four waves.',
'Полная луна':'Full Moon','В полнолуние волки злее. Держись 80 секунд.':'Wolves are fiercer at full moon. Hold out for 80 seconds.',
'Стражи логова':'Lair Guards','У входа в логово дежурят волки. Прогони двадцать.':'Wolves guard the lair entrance. Chase off twenty.',
'Перекрёсток троп':'Crossroads','Все тропы сходятся здесь — и все враги тоже.':'All the trails meet here — and so do all the enemies.',
'Подозрительная тишина':'Suspicious Silence','Лес затих. Это ловушка! Победи 50 врагов.':'The forest went quiet. It’s a trap! Defeat 50 enemies.',
'Серый Хвост вышел из логова. Победи вожака стаи!':'Greytail has left his lair. Defeat the pack leader!',
/* ---------- глава 3 ---------- */
'Птицефабрика доктора Хорька':'Doctor Ferret’s Poultry Factory',
'За лесом дымит труба птицефабрики. Доктор Хорёк собирает там робо-несушек и солдат-хорьков, чтобы захватить все курятники округи.':'Beyond the forest a factory chimney smokes. Doctor Ferret builds robo-hens and ferret soldiers there to seize every coop in the land.',
'Фабрика остановлена. Но в чертежах доктора стоит подпись: «Для Императора Ворона». Над горами собираются чёрные тучи.':'The factory is shut down. But the doctor’s blueprints are signed: “For Emperor Raven.” Black clouds gather over the mountains.',
'Проходная':'The Gate','Вход охраняют хорьки в касках. Прорвись через две волны.':'Ferrets in helmets guard the entrance. Break through two waves.',
'Склад зерна':'Grain Store','Здесь хранят краденое зерно. Держись 45 секунд, пока цыплята уносят мешки.':'Stolen grain is kept here. Hold out for 45 seconds while the chicks carry off the sacks.',
'Конвейер':'Conveyor','С конвейера сходят робо-несушки. Перед выстрелом они целятся красным лучом. Сломай шесть.':'Robo-hens roll off the conveyor. They aim with a red beam before shooting. Break six.',
'Цех упаковки':'Packing Hall','Коробки, ленты и хорьки. Пройди три волны.':'Boxes, belts and ferrets. Clear three waves.',
'Аварийный свет':'Emergency Lights','Доктор вырубил свет на всём заводе. Держись минуту в темноте.':'The doctor cut the power to the whole plant. Hold out for a minute in the dark.',
'Лаборатория':'Laboratory','В колбах — формула роботов. Победи 30 врагов и забери её.':'The robot formula is in the flasks. Defeat 30 enemies and grab it.',
'Полигон':'Test Range','На полигоне испытывают новых роботов. На тебе.':'New robots are being tested on the range. On you.',
'Вентиляция':'Air Vents','Крысы-шпионы бегают по трубам — они крупнее мышей, быстрее и кусаются больно. Поймай 12.':'Spy rats run through the pipes — bigger than mice, faster, and they bite hard. Catch 12.',
'Котельная':'Boiler Room','Жарко и шумно. Продержись 75 секунд у котлов.':'Hot and loud. Hold out for 75 seconds by the boilers.',
'Первый боевой робот фабрики. Разбери его на винтики!':'The factory’s first combat robot. Take it apart bolt by bolt!',
'Склад запчастей':'Spare Parts Store','Из запчастей собирают новых роботов. Помешай сборке.':'New robots are assembled from spare parts. Stop the assembly.',
'Ночная смена':'Night Shift','Заступила ночная смена хорьков. Прогони двадцать.':'The ferret night shift has clocked in. Chase off twenty.',
'Сборочный цех':'Assembly Hall','Роботы сходят с ленты потоком. Держись 75 секунд.':'Robots stream off the line. Hold out for 75 seconds.',
'Пульт управления':'Control Room','Сломай 15 роботов, чтобы пробиться к пульту.':'Break 15 robots to reach the control panel.',
'Сирена':'Siren','Сработала сирена — вся охрана бежит к тебе.':'The siren went off — all the guards are running at you.',
'Кабинет доктора':'Doctor’s Office','Доктор сбежал, оставив охрану. Победи 45 врагов.':'The doctor fled, leaving his guards. Defeat 45 enemies.',
'Секретный лифт':'Secret Elevator','Лифт едет медленно, а враги лезут со всех сторон.':'The elevator is slow, and enemies climb in from every side.',
'Подземный ангар':'Underground Hangar','В ангаре стоит огромный боевой мех. Пробейся к нему.':'A huge battle mech stands in the hangar. Fight your way to it.',
'Предохранители':'Fuses','Выбей предохранители завода — победи 55 врагов.':'Blow the plant’s fuses — defeat 55 enemies.',
'Доктор сам сел за рычаги. Финальная битва на фабрике!':'The doctor took the controls himself. The final battle at the factory!',
/* ---------- глава 4 ---------- */
'Гнездо Императора':'The Emperor’s Nest',
'На вершине горы, в Чёрном Гнезде, сидит Император Ворон. Это он стоял за атаманом, волками и фабрикой. Пора подниматься в гору.':'At the mountain top, in the Black Nest, sits Emperor Raven. He was behind the Chieftain, the wolves and the factory. Time to climb.',
'Император повержен, Чёрное Гнездо пало! Курятники всей округи свободны, а петухи на рассвете поют о тебе песни. Конец… пока что.':'The Emperor is beaten and the Black Nest has fallen! Every coop in the land is free, and roosters sing of you at dawn. The end… for now.',
'Подножие горы':'Foot of the Mountain','Горную тропу охраняют вороны Императора.':'The Emperor’s crows guard the mountain path.',
'Горный ветер':'Mountain Wind','Орлы пикируют сверху — перед броском они замирают. Сбей пятерых.':'Eagles dive from above — they freeze before they strike. Shoot down five.',
'Каменная осыпь':'Rockslide','Сверху летят камни и яйца. Держись 50 секунд.':'Rocks and eggs fall from above. Hold out for 50 seconds.',
'Пещера':'The Cave','В пещере темно и сыро. Пройди три волны.':'The cave is dark and damp. Clear three waves.',
'Перевал':'Mountain Pass','На перевале стоит застава Императора. Победи 35 врагов.':'The Emperor has an outpost on the pass. Defeat 35 enemies.',
'Старая мельница':'The Old Mill','Мельница скрипит на ветру. Держись минуту.':'The mill creaks in the wind. Hold out for a minute.',
'Вороньи гнёзда':'Crow Nests','Разори вороньи гнёзда — сбей 25 ворон.':'Raid the crow nests — shoot down 25 crows.',
'Снежное поле':'Snowfield','Холодно и скользко. Пройди три волны по снегу.':'Cold and slippery. Clear three waves in the snow.',
'Ночной штурм':'Night Assault','Враги идут в атаку под покровом ночи. Держись 80 секунд.':'Enemies attack under cover of night. Hold out for 80 seconds.',
'Генерал воздушных войск Императора. Спусти его на землю!':'The general of the Emperor’s air force. Bring him down to earth!',
'Облачный мост':'Cloud Bridge','Мост из облаков… и из врагов.':'A bridge of clouds… and of enemies.',
'Остатки банд':'Gang Remnants','Все, кто уцелел у атамана, волков и доктора, собрались здесь. Победи 50.':'Everyone left from the Chieftain, the wolves and the doctor has gathered here. Defeat 50.',
'Буря':'The Storm','Гром и молнии. Держись 90 секунд.':'Thunder and lightning. Hold out for 90 seconds.',
'Совиная стража':'Owl Guard','Совы-снайперы стерегут ворота. Сбей пятнадцать.':'Sniper owls guard the gates. Shoot down fifteen.',
'Ворота Гнезда':'Gates of the Nest','Ворота открываются. Пройди четыре волны.':'The gates are opening. Clear four waves.',
'Зал трофеев':'Trophy Hall','Здесь висят украденные перья всех курятников. Победи 55 врагов.':'The stolen feathers of every coop hang here. Defeat 55 enemies.',
'Императорская гвардия':'Imperial Guard','Гвардия бросилась в бой. Держись 100 секунд.':'The guard charges into battle. Hold out for 100 seconds.',
'Тронный коридор':'Throne Corridor','Коридор к трону тонет во тьме. Пройди четыре волны.':'The corridor to the throne is drowned in darkness. Clear four waves.',
'Перед троном':'Before the Throne','Император ждёт. Победи 60 стражей.':'The Emperor awaits. Defeat 60 guards.',
'Последний бой. Победи Императора — и все курятники станут свободными!':'The final battle. Defeat the Emperor and every coop will be free!',
/* ---------- создатели ---------- */
'геймдизайн, тестирование':'game design, testing','креатор, кодер':'creator, coder',
'Обновлён список создателей':'Updated the creators list',
/* ---------- патчноуты ---------- */
'бета':'beta',
'У рек появились притоки: на каждой карте от основного русла отходит рукав со своими мостами, в том числе гнилыми':'Rivers now have tributaries: on every map a branch splits off the main river with its own bridges, rotten ones included',
'Враги ищут дорогу через мосты по всей сети рек, обходят изгибы берега и скользят вдоль воды, а не застревают':'Enemies path through bridges across the whole river network, go around river bends and slide along the bank instead of getting stuck',
'Враги больше не появляются в реке':'Enemies no longer spawn in the river',
'Несушки, Робо-несушки и куриные боссы (Индюк-генерал, Стальной Индюк) перелетают воду — герой по-прежнему не может':'Hens, Robo-Hens and poultry bosses (General Turkey, Steel Turkey) fly over water — your hero still can’t',
'Новый враг — Крыса: крупнее мыши, быстрее, прыгает и больно кусает. Старые мелкие крысы теперь Мыши':'New enemy — the Rat: bigger than a mouse, faster, it lunges and bites hard. The old small rats are now Mice',
'Яичный дождь (ульта Пеструшки и её же в отряде) больше не бьёт по каждому врагу: одна зона там, где врагов гуще всего':'Egg Rain (Speckles’ ultimate, also in the squad) no longer hits every enemy: one zone where enemies are thickest',
'Гуси больше не одинаковые: Бронебой — серый, со стальным нагрудником и наплечником; Медсестра — белая, с красным крестом на крыле, румянцем и ресницами':'The geese no longer look alike: Ironclad is grey with a steel breastplate and pauldron; Nurse is white with a red cross on her wing, rosy cheeks and eyelashes',
'Сундуки: кнопка «Свойства» — у каждого сундука свои шансы на героев, карты героев и карты оружия по редкостям':'Chests: a “Details” button — each chest has its own odds for heroes, hero cards and weapon cards by rarity',
'Враги не залезают внутрь бойца — выстрел в упор больше не пролетает мимо':'Enemies no longer get inside your fighter — point-blank shots no longer miss',
'Камикадзе: раненый враг иногда поджигает фитиль, бежит к тебе и взрывается. Если добить его пулями — он просто взорвётся на месте':'Kamikaze: a wounded enemy sometimes lights a fuse, runs at you and explodes. Finish it with bullets and it just blows up on the spot',
'Пеньки — новое препятствие на картах':'Stumps — a new obstacle on the maps',
'Бомбардировка стала умнее: вороны и боссы бьют то по месту, то по направлению движения, то ковровой цепочкой':'Smarter bombing: crows and bosses aim at your spot, where you’re heading, or drop a carpet chain',
'Новые герои: Перепёлка Тень (снайпер), Цесарка Буря (штурмовик), Гусыня Медсестра (медик) — у каждой своя ульта и пассивки':'New heroes: Shadow Quail (sniper), Storm Guinea (assault), Nurse Goose (medic) — each with her own ultimate and passives',
'Отряд: каждому бойцу можно выбрать оружие своего класса, и бойцы сами применяют свои ульты':'Squad: pick a class weapon for each fighter, and fighters use their own ultimates',
'Медики лечат всех своих в радиусе (игрока и весь отряд), лечение видно зелёными плюсиками; рядом с медиком выбитые бойцы встают вдвое быстрее':'Medics heal every ally in range (player and the whole squad), healing shows as green pluses; near a medic downed fighters get up twice as fast',
'Карточки отряда: кнопки «Сменить оружие» и «Убрать» больше не вылезают за край':'Squad cards: the “Change weapon” and “Remove” buttons no longer overflow',
'Баланс: враги бьют сильнее (×1,3 и +7% за ступень сложности), лечение медиков, кукуруза и лечение за волну слабее, предметы падают реже':'Balance: enemies hit harder (×1.3 and +7% per difficulty step), medic healing, corn and wave-clear healing are weaker, items drop less often',
'Баланс: камикадзе редкие (5%, не больше одного за раз и не чаще раза в 12 секунд), кроты больше не мешают появляться остальным врагам':'Balance: kamikazes are rare (5%, one at a time, at most once per 12 seconds), moles no longer block other enemies from spawning',
'Враги реже переключаются на бойцов отряда — основной удар снова по герою':'Enemies switch to squad members less often — the main pressure is back on the hero',
'Фон главного меню можно выбрать: кнопка «Фон» под бойцом, на выбор все 5 карт':'Pick the main menu background: the “Background” button under your fighter, all 5 maps available',
'Кукуруза-лечилка падает на четверть реже':'Healing corn drops a quarter less often',
'Новое оружие: Пулемёт Турбокота (штурмовик, каждый 6-й выстрел — пробивающий клубок ×3) и Дробовик Фигурки (танк, звёздочки и сердечки рикошетят от укрытий)':'New weapons: Turbo Cat Machine Gun (assault, every 6th shot is a piercing ×3 yarn ball) and Shapes Shotgun (tank, stars and hearts ricochet off cover)',
'Редкость оружия: Обычное, Редкое, Легендарное':'Weapon rarity: Common, Rare, Legendary',
'Карты оружия падают из сундуков: улучшай купленные стволы в магазине до 10 уровня, +6% урона за уровень (и у бойцов отряда тоже)':'Weapon cards drop from chests: upgrade owned guns in the shop up to level 10, +6% damage per level (for squad members too)',
'Новая система сундуков: Обычный, Большой и Сверхбольшой. Внутри — новые герои или карты к ним, карты оружия, зёрна и золотые яйца. Герои выпадают только из сундуков':'New chest system: Common, Big and Mega. Inside — new heroes or their cards, weapon cards, grain and golden eggs. Heroes only come from chests',
'Сверхбольшой сундук: гарантированный новый герой, пока есть закрытые. Даётся за финального босса каждой главы и за 25-ю волну бесконечного боя, или за 200 золотых яиц':'Mega chest: a guaranteed new hero while any are locked. Earned for each chapter’s final boss and for wave 25 in Endless, or for 200 golden eggs',
'Реки на всех картах: по воде ходить нельзя, переходи по мостам. Гнилые мосты скрипят и рушатся после второго прохода':'Rivers on every map: you can’t walk on water, cross by bridges. Rotten bridges creak and collapse after the second crossing',
'5 карт со своей рекой: Двор (бесконечный бой), Ферма, Тёмный лес, Птицефабрика и Горы — по одной на главу':'5 maps, each with its own river: Yard (Endless), Farm, Dark Forest, Poultry Factory and Mountains — one per chapter',
'Враги и отряд ищут дорогу через целые мосты':'Enemies and the squad find their way across intact bridges',
'Кроты: во время раунда вырываются ямки, из них вылезают кроты-шахтёры и кидаются землёй, а потом ямки зарываются':'Moles: holes burst open during a round, miner moles climb out and throw dirt, then the holes close up',
'Кнопка «Об игре»: создатели, версия и патчноуты; номер версии берётся из патчноутов':'“About” button: creators, version and patch notes; the version number comes from the patch notes',
'Крупнее и удобнее кнопки: пауза, звук, граната, ульта, вкладки и кнопки в магазине':'Bigger, easier buttons: pause, sound, grenade, ultimate, tabs and shop buttons',
'Сюжет: 4 главы по 20 уровней, 8 боссов, ночные уровни':'Story: 4 chapters of 20 levels, 8 bosses, night levels',
'Бесконечный бой с волнами':'Endless battle with waves',
'6 героев 4 редкостей, прокачка картами до 10 уровня, пассивки на 5 и 10, ульты':'6 heroes of 4 rarities, card upgrades to level 10, passives at 5 and 10, ultimates',
'Классы: Штурмовик, Танк, Снайпер, Медик — свои бонусы и своё оружие':'Classes: Assault, Tank, Sniper, Medic — each with its own bonuses and weapons',
'15 основных стволов, временные стволы и яйца-гранаты':'15 main guns, temporary guns and egg grenades',
'Отряд до 3 бойцов':'Squad of up to 3 fighters',
'Сундуки, жетоны, большие жетоны, золотые яйца':'Chests, tokens, big tokens, golden eggs',
'Магазин шапок, окрасов и оружия':'Shop for hats, colours and weapons',
'Лобби-меню; «Многопользовательская игра» и «Режим Soul Knight» пока закрыты':'Lobby menu; “Multiplayer” and “Soul Knight mode” are locked for now',
'Настройки: язык (русский или английский), громкость музыки и звуков, тряска экрана, автонаводка':'Settings: language (Russian or English), music and sound volume, screen shake, auto-aim',
'Английский язык: переведены меню, герои, оружие, враги, все 80 уровней сюжета и патчноуты':'English language: menus, heroes, weapons, enemies, all 80 story levels and patch notes are translated',
'Музыка: своя мелодия для меню, боя и боссов':'Music: separate tunes for the menu, battles and bosses',
'В паузе появились кнопки «Заново» и «Настройки»; кнопка автонаводки переехала в настройки':'The pause menu now has “Restart” and “Settings” buttons; the auto-aim button moved to settings',
'Исправлено: после проигрыша и перезапуска больше не всплывает номер прошлой волны':'Fixed: after losing and restarting, the previous wave number no longer flashes on screen',
/* ---------- интерфейс: бой ---------- */
'огонь':'fire','бег':'move','Глава ':'Chapter ','Волна 25! Сверхбольшой сундук ждёт в меню':'Wave 25! A Mega chest awaits in the menu',
'Волна ':'Wave ',' впервые! +':' for the first time! +',' золотых яиц':' golden eggs',' из ':' of ',
'Защити курятник!':'Defend the coop!','Лисы почуяли запах':'The foxes caught the scent','Пришли индюки':'Here come the turkeys','Вороны в небе!':'Crows in the sky!',
'Еноты вышли на охоту':'Raccoons are on the hunt','Врагов всё больше':'More and more enemies','+1 яйцо':'+1 egg','Босс вышел на поле!':'A boss has entered the field!',
'Блок':'Block','Мимо!':'Missed!','Уклон!':'Dodge!','Второе дыхание!':'Second wind!','Утка снова в строю':'The duck is back in action',' выбит':' is down',
'Снова в бою!':'Back in the fight!','КРИТ ':'CRIT ','КАМИКАДЗЕ!':'KAMIKAZE!','Патроны кончились':'Out of ammo',' здоровья':' HP','КУКАРЕКУ!':'COCK-A-DOODLE-DOO!','Поднят!':'Revived!',
'Победи: ':'Defeat: ','Продержись ':'Survive ','Держись ':'Hold ','Победи босса':'Defeat the boss','Босс: ':'Boss: ',' очк.':' pts','Комбо ×':'Combo ×',' с':' s','УЛЬТА':'ULT',
'Ур. ':'Lv. ',' · отряд: ':' · squad: ','Все 4 главы пройдены · можно переигрывать':'All 4 chapters cleared · replay any level','Рекорд: волна ':'Record: wave ',
'Рекорда пока нет — поставь первый':'No record yet — set the first one','Уровень':'Level','Уровень «':'Level “','» не пройден. Попробуй ещё раз!':'” failed. Try again!','Волна':'Wave',
'Курятник пал на волне ':'The coop fell on wave ','Заработано: <i class="coin"></i>':'Earned: <i class="coin"></i>',' зёрен · <i class="tok"></i>':' grain · <i class="tok"></i>',' жетонов':' tokens',
'Победа!':'Victory!',' · уровень ':' · level ',' из 20':' of 20','» пройден.':'” cleared.',' зёрен':' grain','награда за первое прохождение':'first-clear reward','повторное прохождение':'replay',
'на обычный сундук: ':'for a Common chest: ','только за первое прохождение':'first clear only','<i class="sch"></i>Сверхбольшой сундук!':'<i class="sch"></i>Mega chest!',
'за финального босса главы · открой в «Сундуках»':'for the chapter’s final boss · open it in “Chests”','<i class="btok"></i>+1 большой жетон':'<i class="btok"></i>+1 big token',
'на большой сундук: ':'for a Big chest: ','/10 · следующий завтра':'/10 · next one tomorrow','<i class="btok"></i>Большой жетон уже получен сегодня':'<i class="btok"></i>Today’s big token already earned',
'завтра пройди уровень ещё раз':'clear a level again tomorrow','Уровень ':'Level ','Версия ':'Version ',
'Двор чист!':'Yard cleared!',' зёрен · +3 жетона':' grain · +3 tokens','В атаку!':'Attack!','Берегись неба!':'Watch the sky!',
'Двор':'Yard','Ферма':'Farm','Птицефабрика':'Poultry Factory','Горы':'Mountains','Скрип… мост гнилой':'Creak… the bridge is rotten','Трещит! Сейчас рухнет':'Cracking! It’s about to fall','Мост рухнул!':'The bridge collapsed!',
/* ---------- интерфейс: меню ---------- */
'Выбрано':'Selected','Выбрать':'Select','Не хватает ':'Short by ','Куплено!':'Purchased!','Шапки':'Hats','Надето: ':'Wearing: ','Окрас':'Colour','Окрас: ':'Colour: ',
'У каждого класса своё оружие: герой берёт в бой только стволы своего класса. Сейчас в бою ':'Each class has its own weapons: a hero only takes guns of their class into battle. Now fighting: ',
' — класс «':' — class “','». Патроны у основного ствола бесконечные.':'”. Your main gun has infinite ammo.',' · твой класс':' · your class','Урон ':'Damage ',' выстр/с · ≈':' shots/s · ≈',' в сек':' per sec',
' из 10':' of 10',' · урон +':' · damage +','<div class="progt"><span>Карты оружия</span><span>':'<div class="progt"><span>Weapon cards</span><span>','Улучшить · ':'Upgrade · ',
'Нужно ещё ':'Need ',' карт оружия — они падают из сундуков':' more weapon cards — they drop from chests',': уровень ':': level ',' карт — открывай сундуки':' more cards — open chests',
'Уровень 5! Пассивка «':'Level 5! Passive “','» и +3 золотых яйца':'” and +3 golden eggs','Уровень 10! Пассивка «':'Level 10! Passive “','» и +10 золотых яиц':'” and +10 golden eggs',
'Новых героев выбивают из сундуков. Карты героя из сундуков вместе с зёрнами повышают его уровень: +6% здоровья и +5% урона за уровень. На 5-м уровне открывается первая пассивка, на 10-м вторая.':'New heroes come from chests. Hero cards from chests plus grain raise a hero’s level: +6% HP and +5% damage per level. The first passive unlocks at level 5, the second at level 10.',
'Отряд':'Squad',
'Бойцы отряда (зелёный круг под ногами) идут рядом, стреляют из выбранного оружия, сами применяют ульту (жёлтая полоска под здоровьем) и принимают удары на себя. Если бойца выбили, через 18 секунд он возвращается, а рядом с живым медиком — вдвое быстрее. Сила зависит от уровня героя. Места в отряде открываются за золотые яйца.':'Squad members (green circle underfoot) walk beside you, fire their chosen weapon, use their ultimate on their own (yellow bar under HP) and take hits for you. A downed fighter returns after 18 seconds, twice as fast near a living medic. Strength depends on the hero’s level. Squad slots unlock for golden eggs.',
'Место ':'Slot ',' · ульта: ':' · ult: ','Оружие: <b>':'Weapon: <b>',' · купи ещё стволы класса в магазине':' · buy more class guns in the shop','Сменить оружие':'Change weapon',
'У класса «':'The “','» пока один ствол — купи ещё в магазине':'” class has only one gun so far — buy more in the shop','Убрать из отряда':'Remove from squad','Боец ушёл из отряда':'Fighter left the squad',
'Свободно':'Empty','Нажми «В отряд» у героя ниже':'Tap “To squad” on a hero below','Закрыто':'Locked','Открыть · ':'Unlock · ','Сначала открой место ':'First unlock slot ',
'Герои':'Heroes','Не открыт':'Locked','. Оружие: <b>':'. Weapon: <b>','<span class="k">УЛЬТА</span><b>':'<span class="k">ULT</span><b>','<span class="k">УР. 5</span><b>':'<span class="k">LV. 5</span><b>',
'<span class="k">УР. 10</span><b>':'<span class="k">LV. 10</span><b>','<div class="progt"><span>Карты до ур. ':'<div class="progt"><span>Cards to lv. ','Максимальный уровень · карт в запасе: ':'Max level · spare cards: ',
'В бой идёт ':'Going into battle: ','Максимум':'Max','В отряд':'To squad','В отряде нет мест':'No free squad slots',' в отряде!':' joined the squad!','Купи ещё место для отряда':'Buy another squad slot',
'Выпадает как «':'Drops as a “','» герой: ':'” hero: ',' в обычном сундуке, ':' in a Common chest, ',' в большом':' in a Big one','К сундукам':'To chests',' · пройдено ':' · cleared ',
'<span class="k">ФИНАЛ ГЛАВЫ</span>':'<span class="k">CHAPTER FINALE</span>','Глава откроется после победы над финальным боссом главы ':'Unlocks after defeating the final boss of chapter ',
'Пройден':'Cleared','Босс':'Boss','Доступен':'Open','Закрыт':'Locked',' · ночь':' · night',' · повтор: меньше':' · replay: less','Пройди ':'Clear ',
'любых врагов':'any enemies',' секунд':' seconds','Победи босса: ':'Defeat the boss: ','<span>Цель: ':'<span>Goal: ','</span><small>Карта: ':'</span><small>Map: ',
' · река с мостами, гнилые рушатся после второго прохода</small><small>Враги: ':' · river with bridges, rotten ones collapse after the second crossing</small><small>Enemies: ',
'. Ночь — обзор меньше':'. Night — shorter view','</small><small>Награда: ':'</small><small>Reward: ',' зёрен, ':' grain, ',' жетонов</small>':' tokens</small>','Боец: ':'Fighter: ',') · ур. ':') · lv. ',
'Обычный сундук':'Common chest','корзинка несушки':'hen’s basket','Большой сундук':'Big chest','золотое яйцо':'golden egg','Сверхбольшой сундук':'Mega chest','аметистовое яйцо':'amethyst egg',
'<b>i</b>Свойства':'<b>i</b>Details','Свойства: ':'Details: ','шанс золотых яиц':'chance of golden eggs',' зёрен · ':' grain · ',' пачки карт героев · ':' hero card packs · ',' пачки':' packs',' пачка':' pack',
' карт оружия · ':' of weapon cards · ',' · <b>гарантированный новый герой</b>, пока есть закрытые':' · <b>guaranteed new hero</b> while any are locked','Жетоны':'Tokens',
'Жетоны дают за врагов, волны и уровни сюжета.':'Tokens come from enemies, waves and story levels.','Открыть':'Open','<i class="tok"></i>ещё ':'<i class="tok"></i>need ','Большие жетоны':'Big tokens',
'Большой жетон сегодня уже получен, следующий — завтра.':'Today’s big token is already earned, the next one comes tomorrow.','Пройди уровень сюжета сегодня — получишь большой жетон.':'Clear a story level today to earn a big token.',
'<i class="btok"></i>ещё ':'<i class="btok"></i>need ','Большие жетоны: 1 в день за пройденный уровень сюжета':'Big tokens: 1 per day for clearing a story level','Купить · <i class="gegg"></i>':'Buy · <i class="gegg"></i>',
'<b>Есть: ':'<b>You have: ','</b> · по одному за каждого финального босса главы (20-й уровень, первое прохождение) и за 25-ю волну в бесконечном бою.':'</b> · one for each chapter’s final boss (level 20, first clear) and for wave 25 in Endless.',
'Нет в запасе':'None in stock','Победи финального босса главы — получишь сверхбольшой сундук':'Defeat a chapter’s final boss to get a Mega chest',
'У каждого сундука свои шансы — нажми «Свойства» на картинке сундука. Герои выпадают только из сундуков. Карты героев падают только для открытых героев, карты оружия — только для купленных стволов.':'Each chest has its own odds — tap “Details” on the chest picture. Heroes only come from chests. Hero cards drop only for unlocked heroes, weapon cards only for guns you own.',
'Золотые яйца':'Golden eggs','Редкая валюта: у тебя <b>':'Rare currency: you have <b>','</b>. Большой сундук стоит ':'</b>. A Big chest costs ',', сверхбольшой — ':', a Mega chest — ',
'. Где взять: первое прохождение уровней сюжета (3–15 за уровень), волны 10, 15 и 20 в бесконечном бою (один раз), 5-й и 10-й уровень героя, сундуки. Ещё за яйца продаются Нимб, Платиновый окрас и Рельсотрон.':'. Where to get them: first clears of story levels (3–15 per level), waves 10, 15 and 20 in Endless (once), hero levels 5 and 10, chests. Eggs also buy the Halo, the Platinum colour and the Railgun.',
'Всегда внутри':'Always inside','Награда':'Reward','Сколько':'Amount','<i class="coin"></i>Зёрна':'<i class="coin"></i>Grain','Пачки карт героев':'Hero card packs',' карт*':' cards*','Пачки карт оружия':'Weapon card packs',
'<i class="gegg"></i>Золотые яйца':'<i class="gegg"></i>Golden eggs','всегда':'always','шанс ':'chance ','Новый герой':'New hero',' · гарантирован':' · guaranteed','Редкость':'Rarity','Шанс':'Chance','Ещё закрыто':'Still locked',
'<b>Хоть какой-то герой</b>':'<b>Any hero at all</b>','Кому достанется пачка карт':'Who gets the card packs','Карты героя':'Hero cards','Шанс пачки':'Pack chance','Карт в пачке':'Cards per pack','Карты оружия':'Weapon cards',
'Шансы считаются от твоего прогресса: уже открытые герои и стволы на максимальном уровне не выпадают. Сначала проверяется самая высокая редкость героя. * Чем выше редкость, тем меньше карт в пачке.':'Odds are based on your progress: heroes you already have and guns at max level don’t drop. The highest hero rarity is rolled first. * The higher the rarity, the fewer cards per pack.',
'Новый герой · ':'New hero · ','<small>редкая находка!</small>':'<small>a rare find!</small>',' карт · ':' cards · ',' до ур. ':' to lv. ','макс. уровень':'max level',' · улучшай в магазине':' · upgrade in the shop',
'<small>Героя в этот раз нет. Ещё не открыто: ':'<small>No hero this time. Still locked: ','Забрать':'Collect','Фон меню: ':'Menu background: ',
'Многопользовательская игра появится в одном из следующих обновлений':'Multiplayer is coming in a future update','Режим Soul Knight пока в разработке — следи за обновлениями':'Soul Knight mode is in development — stay tuned for updates',
'Автонаводка включена':'Auto-aim on','Автонаводка выключена: целься мышью':'Auto-aim off: aim with the mouse',
/* ---------- статичный HTML ---------- */
'Боевой Курятник':'Battle Coop','Волна 1':'Wave 1','Бум':'Boom','Штурмовик · ур. 1':'Assault · lv. 1','Сменить бойца':'Change fighter','Фон':'Background','Сюжет':'Story',
'Глава 1 · 0/20':'Chapter 1 · 0/20','Бесконечный бой':'Endless battle','Рекорда пока нет':'No record yet','Многопользовательская игра':'Multiplayer','Скоро':'Soon','Режим Soul Knight':'Soul Knight mode',
'Удобнее играть, повернув телефон горизонтально':'Turn your phone sideways for the best experience','Сундуки':'Chests','Магазин':'Shop','Об игре':'About','Как играть':'How to play',
'Информация об игре':'About the game','Версия 0.1':'Version 0.1','Создатели':'Creators','Патчноуты':'Patch notes','Закрыть':'Close','Настройки':'Settings','Язык':'Language','Русский':'Русский',
'Игра перезапустится на выбранном языке':'The game will restart in the selected language','Музыка':'Music','Звуки':'Sounds','Тряска экрана от взрывов':'Screen shake from explosions','Автонаводка':'Auto-aim',
'стреляет сама по ближнему врагу (T)':'fires at the nearest enemy by itself (T)','Готово':'Done','Главное меню':'Main menu','Фон меню':'Menu background',
'Левый палец — бежать':'Left thumb — move','Правый палец — целиться и стрелять. Держи на месте — бьёт по ближнему':'Right thumb — aim and shoot. Hold still to hit the nearest enemy',
'«Бум» — яйцо-граната':'“Boom” — egg grenade','Ульта копится от урона по врагам':'Your ultimate charges as you damage enemies',
'На компьютере: WASD — бег, автонаводка стреляет сама (T — вкл/выкл), зажатая мышь — ручная стрельба, Q — граната, R — ульта':'On a computer: WASD — move, auto-aim fires by itself (T — on/off), hold the mouse — manual fire, Q — grenade, R — ultimate',
'Понятно':'Got it','Продолжить':'Resume','Заново':'Restart','В меню':'Main menu','Ощипали!':'Plucked!','Курятник пал на волне 1.':'The coop fell on wave 1.','Заработано: 0':'Earned: 0',
'Очки':'Score','Новый рекорд!':'New record!','Ещё раз':'Again','Уровень 1':'Level 1','Двор отбит.':'Yard defended.','Следующий уровень':'Next level','Название':'Title','Текст':'Text','Боец':'Fighter',
'В бой!':'Fight!','Назад':'Back','Свойства сундука':'Chest details','Сундук':'Chest','Скины':'Skins','Оружие':'Weapons','Игровое поле':'Playing field','Звук':'Sound','Ульта':'Ultimate',
'Бросить яйцо-гранату':'Throw an egg grenade','Кошелёк':'Wallet','Зёрна':'Grain','Жетоны на обычный сундук':'Tokens for a Common chest','Твой боец':'Your fighter','Выбрать фон меню':'Pick menu background',
/* ---------- 0.4: способности, экономика, магазин ---------- */
'«КУКАРЕКУ!» оглушает всех рядом на 2,5 с, бьёт на 45, и 4 с Петя получает вдвое меньше урона':"“COCK-A-DOODLE-DOO!” stuns everyone nearby for 2.5 s, deals 45, and for 4 s Pete takes half damage",
'Плавает: переходит реки вплавь (в воде медленнее) и лечится сама, если 4 секунды не получала урон':"Swims: crosses rivers by swimming (slower in water) and heals herself after 4 seconds without damage",
'Лечит половину здоровья себе и бойцам рядом, сбивает яйца, отталкивает врагов и оставляет лужу, в которой враги вязнут':"Heals half HP to herself and nearby fighters, knocks down eggs, pushes enemies away and leaves a puddle that bogs enemies down",
'Утиный нырок':"Duck Dive",
'В воде утка ныряет: пули и яйца пролетают над ней':"In water the duck dives: bullets and eggs fly over her",
'5 секунд неуязвимости, вражеские яйца отлетают обратно, а в конце — ударная волна на 70':"5 seconds of invulnerability, enemy eggs bounce back, and at the end — a 70-damage shockwave",
'Три пробивающих луча в самых крепких врагов, а потом 3 с невидимости: враги теряют Перепёлку из виду':"Three piercing beams at the toughest enemies, then 3 s of invisibility: enemies lose sight of the Quail",
'Пёстрая и шустрая: каждый 8-й выстрел — веер из 5 острых перьев':"Speckled and nimble: every 8th shot is a fan of 5 sharp feathers",
'4 с вихрь затягивает врагов к Цесарке, бьёт их и сбивает пули, а в конце раскидывает взрывом':"For 4 s a whirlwind pulls enemies to the Guinea, hits them and knocks down shots, then flings them away with a blast",
'Аптечки: каждые 15 с бросает аптечку (+25 здоровья) самому раненому из своих':"Medkits: every 15 s throws a medkit (+25 HP) to the most wounded ally",
'Легенда двора: каждый 5-й выстрел — огненный снаряд, который взрывается и поджигает врагов':"Legend of the yard: every 5th shot is a fireball that explodes and sets enemies ablaze",
'6 с ярости: огненные кольца пуль, +40% скорости, а каждый убитый враг взрывается огнём':"6 s of rage: rings of fire bullets, +40% speed, and every enemy killed bursts into flames",
'Зерно прошивает троих, а при попадании лопается на 3 осколка':"Kernels pierce three and burst into 3 fragments on hit",
'Ледяные иглы замедляют врагов вдвое, а 4 попадания подряд замораживают на 1,2 с':"Ice needles slow enemies by half, and 4 hits in a row freeze them for 1.2 s",
'Урон 10 · 10 выстр/с · замедление 50% · заморозка':"Damage 10 · 10 shots/s · 50% slow · freeze",
'Струя огня поджигает всех врагов перед тобой, а горящие при смерти поджигают соседей':"A stream of fire ignites every enemy in front of you, and burning enemies ignite their neighbours when they die",
'Тяжёлый болт пробивает четверых и пригвождает их на полсекунды':"A heavy bolt pierces four and pins them for half a second",
'креатор, геймдизайн, тестирование':"creator, game design, testing",
'Волна босса!':"Boss wave!",
'Нырок!':"Dive!",
'<i class=\"btok\"></i>Большой жетон — за первое прохождение':"<i class=\"btok\"></i>Big tokens — for first clears",
'или каждые 10 волн в бесконечном бою':"or every 10 waves in Endless",
'Скины теперь у каждого героя свои — вернули за покупки: ':"Every hero now has their own skin — refunded for your purchases: ",
'Наборы золотых яиц появятся позже — пока кнопки закрыты.':"Golden egg packs are coming later — the buttons are locked for now.",
'Донат пока закрыт — скоро откроем':"Purchases are locked for now — coming soon",
'Зёрна за золотые яйца':"Grain for golden eggs",
'Обменяй золотые яйца на зёрна: чем больше набор, тем выгоднее.':"Trade golden eggs for grain: the bigger the pack, the better the deal.",
'Большой жетон дают за первое прохождение каждого уровня сюжета и за каждые 10 волн в бесконечном бою.':"Big tokens come from the first clear of every story level and every 10 waves in Endless.",
'Есть: ':"You have: ",
' · по одному за каждого финального босса главы (20-й уровень, первое прохождение) и за 25-ю волну в бесконечном бою.':" · one for each chapter’s final boss (level 20, first clear) and for wave 25 in Endless.",
'Сколько открыть':"How many to open",
'ещё ':"need ",
'Большие жетоны: за первое прохождение уровня сюжета и каждые 10 волн в бесконечном бою':"Big tokens: for first story level clears and every 10 waves in Endless",
'+1 большой жетон за 10 волн':"+1 big token for 10 waves",
'Горстка яиц':"Handful of eggs",
'Корзинка яиц':"Basket of eggs",
'Лукошко яиц':"Hamper of eggs",
'Ящик яиц':"Crate of eggs",
'Телега яиц':"Cart of eggs",
'Хит':"Popular",
'Золотой курятник':"Golden coop",
'Выгодно':"Best value",
'Мешочек зерна':"Pouch of grain",
'Мешок зерна':"Sack of grain",
'Амбар зерна':"Barn of grain",
'Золотые яйца':"Golden eggs",
'Язык меняется сразу, без перезапуска — окно настроек и бой остаются на месте':"The language switches instantly, without a restart — the settings window and your battle stay put",
'Музыка включается с первого касания, а не после захода в настройки':"Music starts on your first tap, not only after opening settings",
'У каждого героя свои способности, и чем реже герой, тем они интереснее: Утка плавает по рекам, Медсестра бросает аптечки, Петя после клича получает вдвое меньше урона, Перепёлка уходит в тень, Цесарка стреляет веером перьев и затягивает врагов в вихрь, Бронебой бьёт ударной волной, Adrenaline стреляет огненными снарядами':"Every hero has their own abilities, and the rarer the hero, the cooler they are: the Duck swims across rivers, the Nurse throws medkits, Pete takes half damage after his cry, the Quail vanishes into shadow, the Guinea fires feather fans and pulls enemies into her whirlwind, Ironclad hits with a shockwave, Adrenaline fires fireballs",
'Редкое и легендарное оружие стреляет интереснее: попкорн лопается на осколки, морозилка замораживает, арбалет пригвождает, огонь перекидывается на соседей':"Rare and legendary weapons fire in more interesting ways: popcorn bursts into fragments, the Freezer freezes solid, the crossbow pins enemies, fire spreads to neighbours",
'Большой жетон теперь даётся за первое прохождение каждого уровня и за каждые 10 волн бесконечного боя':"A big token now comes from every first level clear and every 10 waves in Endless",
'Бесконечный бой: каждые 5 волн выходит босс':"Endless: a boss appears every 5 waves",
'Места в отряде продаются только за золотые яйца: 50, 100 и 250':"Squad slots are sold only for golden eggs: 50, 100 and 250",
'Сундуки можно открывать сразу по 3 и по 10':"Chests can be opened 3 or 10 at a time",
'У каждого героя свой фирменный образ; скины из магазина убраны, потраченное на них вернули':"Every hero has a signature look; skins are gone from the shop and what you spent on them was refunded",
'Магазин: раздел «Золотые яйца» с наборами на 39, 79, 179, 309, 749 и 1999 яиц (пока закрыты) и обменом яиц на зёрна':"Shop: a “Golden eggs” section with packs of 39, 79, 179, 309, 749 and 1999 eggs (locked for now) and an eggs-for-grain exchange",
'Режимы':'Modes','Разделы':'Sections','Пауза':'Pause'
};
/* Перевод на лету: при первом вызове запоминаем русские оригиналы данных и страницы,
   дальше applyLang() просто подставляет русскую или английскую строку — без перезагрузки */
const I18N={recs:[],nodes:[],attrs:[],ready:false};
function i18nCollect(){
  const CYR=/[А-Яа-яЁё]/, seen=new Set();
  (function walk(o){if(!o||typeof o!=='object'||seen.has(o))return;seen.add(o);
    for(const k of Object.keys(o)){const v=o[k];if(typeof v==='string'){if(CYR.test(v))I18N.recs.push({o,k,ru:v});}else walk(v);}})
  ([HEROES,WEAP,CLASSES,RAR,WRAR,HATS,COLORS,ETYPE,KILLN,CHAPTERS,STORY,PATCH_NOTES,CREDITS,MAPS,CHESTS,GEM_PACKS,GRAIN_PACKS]);
  const tw=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;
  while((n=tw.nextNode())){const s=n.nodeValue.trim();if(s&&CYR.test(s))I18N.nodes.push({n,full:n.nodeValue,ru:s});}
  document.querySelectorAll('[aria-label],[title]').forEach(el=>['aria-label','title'].forEach(a=>{const v=el.getAttribute(a);if(v&&CYR.test(v))I18N.attrs.push({el,a,ru:v});}));
  I18N.ready=true;
}
function applyLang(){
  if(!I18N.ready)i18nCollect();
  const tr=s=>LANG==='en'&&EN[s]!==undefined?EN[s]:s;
  for(const r of I18N.recs)r.o[r.k]=tr(r.ru);
  for(const r of I18N.nodes)r.n.nodeValue=r.full.replace(r.ru,tr(r.ru));
  for(const r of I18N.attrs)r.el.setAttribute(r.a,tr(r.ru));
  document.title=tr('Боевой Курятник'); document.documentElement.lang=LANG;
}
